#!/usr/bin/env bash
# Exercise 02: Cross-Compilation
#
# Run: bash training/07-advanced/exercises/e02-cross.sh
#
# Explore cross-compilation with Nix.

set -euo pipefail

echo "═══ Exercise 1: List available cross systems ═══"
echo ""
echo "nixpkgs provides pkgsCross with many target platforms."
echo ""
echo "Some common ones (try in nix repl):"
echo "  pkgs = import <nixpkgs> {}"
echo "  builtins.attrNames pkgs.pkgsCross | head"
echo ""
echo "Common targets:"
echo "  aarch64-multiplatform  — ARM64 Linux (Raspberry Pi 4, cloud servers)"
echo "  raspberryPi            — ARM 32-bit (older Pis)"
echo "  riscv64                — RISC-V 64-bit"
echo "  mingwW64               — Windows (MinGW)"
echo "  musl64                 — x86_64 Linux with musl (for static linking)"
echo ""

echo "═══ Exercise 2: Compare native vs cross derivation ═══"
echo ""
echo "TODO: In nix repl, compare these two:"
echo ""
echo "  pkgs = import <nixpkgs> {}"
echo ""
echo "  # Native hello:"
echo "  pkgs.hello.stdenv.hostPlatform.system"
echo "  # → your current system (e.g., aarch64-darwin)"
echo ""
echo "  # Cross-compiled hello for aarch64-linux:"
echo "  pkgs.pkgsCross.aarch64-multiplatform.hello.stdenv.hostPlatform.system"
echo "  # → aarch64-linux"
echo ""
echo "  # The build platform stays the same:"
echo "  pkgs.pkgsCross.aarch64-multiplatform.hello.stdenv.buildPlatform.system"
echo "  # → aarch64-darwin (your machine)"
echo ""

echo "═══ Exercise 3: Inspect a cross derivation ═══"
echo ""
echo "TODO: Compare the .drv files:"
echo ""
echo "  nix derivation show nixpkgs#hello > /tmp/native-hello.json"
echo "  nix derivation show nixpkgs#pkgsCross.aarch64-multiplatform.hello > /tmp/cross-hello.json"
echo ""
echo "  diff /tmp/native-hello.json /tmp/cross-hello.json | head -50"
echo ""
echo "Look for differences in:"
echo "  - system (build platform)"
echo "  - env.buildInputs vs env.nativeBuildInputs"
echo "  - The compiler used (gcc vs cross-gcc)"
echo ""

echo "═══ Exercise 4: Static linking ═══"
echo ""
echo "TODO: Try building a statically-linked hello:"
echo ""
echo "  nix build nixpkgs#pkgsStatic.hello"
echo "  file result/bin/hello"
echo ""
echo "  # On Linux, you should see 'statically linked'"
echo "  # On macOS, static linking works differently (Mach-O)"
echo ""

echo "═══ Exercise 5: nativeBuildInputs correctness ═══"
echo ""
echo "Read your overlays/direnv-overlay.nix:"
echo "  It uses overrideAttrs to patch the build."
echo "  postPatch runs on the BUILD machine."
echo "  substituteInPlace is a build-time tool (from stdenv, a nativeBuildInput)."
echo ""
echo "Q: Would this overlay work correctly in a cross-compilation scenario?"
echo "A: Yes — postPatch runs on the build machine, and substituteInPlace"
echo "   is a shell function from stdenv which is always available on the build machine."
echo ""

echo "═══ Summary ═══"
echo ""
echo "Key commands to remember:"
echo "  pkgs.pkgsCross.<target>.hello    — cross-compile hello"
echo "  pkgs.pkgsStatic.hello            — static hello"
echo "  stdenv.hostPlatform.system       — what arch the binary runs on"
echo "  stdenv.buildPlatform.system      — what arch builds it"
