name: Flake Sanity Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "NixOS - zeus"
            system: "x86_64-linux"
            config: "zeus"
          - name: "NixOS - vizzia"
            system: "x86_64-linux"
            config: "vizzia"
          - name: "Darwin - mbp2023"
            system: "aarch64-darwin"
            config: "mbp2023"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake
        run: nix flake check

      - name: Show flake info
        run: nix flake show

      - name: Build configuration
        run: |
          nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel \
            --system ${{ matrix.system }} \
            --no-link \
            --print-out-paths



      - name: Check for evaluation errors
        run: |
          nix eval .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel \
            --system ${{ matrix.system }} \
            --json